# Omakase Ruby styling for Rails
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Style/Documentation:
  Enabled: false
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
