# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.6'

gem 'blueprinter', '~> 1.1'
gem 'bootsnap', require: false
gem 'devise', '~> 4.9'
gem 'puma', '>= 5.0'
gem 'pundit', '~> 2.4'
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.2.2'
gem 'sqlite3', '>= 1.4'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
end

group :test do
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.5'
  gem 'rspec-core', '~> 3.13'
  gem 'rspec-expectations', '~> 3.13'
  gem 'rspec-mocks', '~> 3.13'
  gem 'rspec-rails', '~> 7.1'
end
